apiVersion: v1
kind: Namespace
metadata:
  name: devops-system
---
# Source: reloader/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-operator-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-reloader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devops-operator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-system
---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader
  namespace: devops-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: devops-reloader
  template:
    metadata:
      labels:
        app: devops-reloader
    spec:
      containers:
      - image: 364554757/reloader:dev-68b48bc
        args:
          - --leader-elect=true
        imagePullPolicy: IfNotPresent
        name: devops-reloader
#          resources:
#            limits:
#              cpu: 2000m
#              memory: 3000Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: default
